### ISSUE TITLE
Issues in Termination Rate Import Mapper module

### ISSUE THREAD

**Issue by dev-astpp** [iNextrix/ASTPP#149]
#146 
1. Page redirect to dashboard when click on "Process Records" without select any option from drop down
2. Sometimes it show php error in import page but not reproduce each time

3. When I import Invalid file it show array (check image no 1)
![1 import invalid file error](https://cloud.githubusercontent.com/assets/20809954/20058027/c7b44920-a514-11e6-8b31-faa6d11b25c6.jpg)
4. Alignment is not proper in import page (check image no 2)
![2 import mapper](https://cloud.githubusercontent.com/assets/20809954/20058028/c7b79f1c-a514-11e6-9645-f59fc4d17a07.jpg)
5. Import page issues (check image no 3)
![3 map csv to termination rates](https://cloud.githubusercontent.com/assets/20809954/20058029/c7b9ff50-a514-11e6-9c01-a1db452c9010.png)
6. Error file is not download it show blank page (Check image no 4)
![4 download error](https://cloud.githubusercontent.com/assets/20809954/20058030/c7ba3718-a514-11e6-96d9-8aec8079a972.jpg)

**Comment by countrdd** [comment]
These have been fixed.

**Comment by dev-astpp** [comment]
#146 
Hello,

We have test your resolved bugs still few are remain which are : - 
1. Alignment is not proper in import page also there is one label Record not understood the meaning of that label  (check image no 1)
![1](https://cloud.githubusercontent.com/assets/20809954/20561715/eaeae87a-b1a5-11e6-83d5-a7ddb31620c5.jpg)

2. Error file is not download it show blank page (Check image no 2)
![2](https://cloud.githubusercontent.com/assets/20809954/20561742/0d645e22-b1a6-11e6-9c7d-0e09e21a6edc.jpg)

3. When I upload any invalid csv file or sample file that time it returns php error (check image no 3)
![3](https://cloud.githubusercontent.com/assets/20809954/20561766/30755aec-b1a6-11e6-8aa6-92abca9b01fa.jpg)

4. When we click on cancel button in "Import with field map" page it redirect to Dashboard

5. Import with field map preview page sequence need some change 
 i) First character should be in capital
ii) Label should be in this sequence  (Code, Destination, Connect Cost, Include Seconds, Per Minute Cost , Initial Increment, Increment, Priority, Strip, Prepend)
![5](https://cloud.githubusercontent.com/assets/20809954/20562253/a85ae322-b1a8-11e6-83a7-be82e6649344.jpg)

**Comment by countrdd** [comment]
Can you give me an example of the invalid csv you sent?

**Comment by smrdoshi** [comment]
We integrated feature fully into Version 3.5.
